### ISSUE TITLE
No primary site exists

### ISSUE THREAD

**Issue by bdfpplinsinga** [davidhellmann/craftcms-baukasten#95]
So lots of tries i almost got you repo working. But when i use your config i get 'No primary site exists'.

Then when i remove the config it seems to work. Then i can loggin to the admin and see all fields, settings and more. But then when i try to acces the front end i get "Invalid path alias: @assetsUrl".

Do you have any idea?

**Comment by davidhellmann** [comment]
Hey!

can you share your .env file? 
Spontaneously I would say there are env variables missing but not sure.

**Comment by bdfpplinsinga** [comment]
Hi there,

Offcourse i can. Its just you example and added my database credentials and things you mentioned in your readme. So not sure what im missing.

```
# General settings
CRAFT_ENVIRONMENT=dev
CRAFT_SECURITY_KEY=31R0o1E1cpvVAZY7_N0fNDaNG2Lo3bnR
TEST_MAIL=your@mail.com
SYSTEM_MAIL=your@mail.com
REPLY_MAIL=your@mail.com

# Blitz settings
ENABLE_BLITZ_CACHING=0

# ImagerX
FALLBACK_IMAGE=/assets/templateImages/placeholder.png
# MOCK_IMAGE=/assets/templateImages/placeholder.png

# Custom Settings
HARD_MODE=1
LOCAL_DEV_PERFORMANCE=0

# Database
CRAFT_DB_DRIVER=mysql
CRAFT_DB_SERVER=127.0.0.1
CRAFT_DB_PORT=3306
CRAFT_DB_USER=root
CRAFT_DB_PASSWORD=
CRAFT_DB_DATABASE=baukast
CRAFT_DB_SCHEMA=public
CRAFT_DB_CHARSET=utf8mb4
CRAFT_DB_COLLATION=utf8mb4_unicode_ci
CRAFT_DB_TABLE_PREFIX=

# URL & Paths
ASSETS_URL=http://baukast.test/assets
SITE_URL=http://baukast.test
WEB_ROOT_PATH=.

# Vite
VITE_DEV_SERVER_PUBLIC=http://localhost:3100/
VITE_DEV_SERVER_INTERNAL=http://localhost:3100/

# Redis
CRAFT_APP_ID=baukasten
REDIS_HOSTNAME=127.0.0.1
REDIS_PORT=6380
REDIS_DEFAULT_DB=0
REDIS_CRAFT_DB=1

# MailGun
MAILGUN_SYSTEM_MAIL=
MAILGUN_DOMAIN=
MAILGUN_API_KEY=
MAILGUN_ENDPOINT=

# Plugins
PLUGIN_BLITZ=U9QKTMZNFIUFC0FI90EHWIE9
PLUGIN_FORMIE=O93RLZT58J3GS61PB1Y4FRZV
PLUGIN_IMAGERX=YJJ8P7KLYP8N73FGNVXDC2Y4
PLUGIN_NAVIGATION=FO3QCK4KH1G1DLQA5QVTLDLU
PLUGIN_SEOMATIC=MZK1VHT16A7I5FZG57KA7Q4Z
PLUGIN_SUPER_DYNAMIC_FIELDS=PLHH8V2HC9JBVJALP5HWJDPO
PLUGIN_HYPER=IGUW1NIF2L5178YK1A27ZVLE

# Xdebug
DBGP_IDEKEY=phpstorm

# Dev mode
DEV_MODE=true
```

**Comment by bdfpplinsinga** [comment]
Nevermind. I needed to edit a redis server. Now its working. But making redis optional? I saw you had this added but how does it work?

**Comment by davidhellmann** [comment]
Yep should be optional. have a look tomorrow or wednesday. Bit busy these days, sorry.

**Comment by davidhellmann** [comment]
I think you have to use the dev/craft-vite branch. It's more up2date. 

Here is the redis commit. 

https://github.com/davidhellmann/craftcms-baukasten/commit/f17ac0d8d1be3e43d34f6ae4019da49c344c2932
